version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gopalgautam/assignment
    container_name: assignment-container
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./:/usr/src/assignment
